//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaraFunControl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<action type=\"getStatus\"></action>")]
        public string getStatus {
            get {
                return ((string)(this["getStatus"]));
            }
            set {
                this["getStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<action type=\"getCatalogList\"></action>")]
        public string getCatalogList {
            get {
                return ((string)(this["getCatalogList"]));
            }
            set {
                this["getCatalogList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<action type=\"setVolume\" volume_type=\"general\">{0}</action>")]
        public string general {
            get {
                return ((string)(this["general"]));
            }
            set {
                this["general"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<action type=\"setVolume\" volume_type=\"bv\">{0}</action>")]
        public string bv {
            get {
                return ((string)(this["bv"]));
            }
            set {
                this["bv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<action type=\"setVolume\" volume_type=\"lead1\">{0}</action> ")]
        public string lead1 {
            get {
                return ((string)(this["lead1"]));
            }
            set {
                this["lead1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<action type=\"setVolume\" volume_type=\"lead2\">{0}</action> ")]
        public string lead2 {
            get {
                return ((string)(this["lead2"]));
            }
            set {
                this["lead2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<action type=\"play\"></action>")]
        public string play {
            get {
                return ((string)(this["play"]));
            }
            set {
                this["play"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<action type=\"pause\"></action>")]
        public string pause {
            get {
                return ((string)(this["pause"]));
            }
            set {
                this["pause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<action type=\"next\"></action>")]
        public string next {
            get {
                return ((string)(this["next"]));
            }
            set {
                this["next"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<action type=\"seek\">{0}</action> ")]
        public string seek {
            get {
                return ((string)(this["seek"]));
            }
            set {
                this["seek"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<action type=\"pitch\">{0}</action>")]
        public string pitch {
            get {
                return ((string)(this["pitch"]));
            }
            set {
                this["pitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<action type=\"tempo\">{0}</action>")]
        public string tempo {
            get {
                return ((string)(this["tempo"]));
            }
            set {
                this["tempo"] = value;
            }
        }
    }
}
